// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/HelloWorld.tsx";
import * as $$$$$$1 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "site/sections/HelloWorld.tsx": $$$$$$0,
    "site/sections/Theme/Theme.tsx": $$$$$$1,
  },
  "apps": {
    "site/apps/site.ts": $$$$$$$$$$$0,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
